trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'my-vm-ssh'
      sourceFolder: '.'
      targetFolder: '/home/azureuser/playground'
      cleanTargetFolder: false
      overwrite: true

  - task: SSH@0
    inputs:
      sshEndpoint: 'my-vm-ssh'
      script: |
        cd /home/azureuser/playground
        sudo docker build -t rust-runner .
        nohup node server.js > server.log 2>&1 &